<?php

namespace AppBundle\Repository;

/**
 * SpaceMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpaceMissionRepository extends \Doctrine\ORM\EntityRepository
{
}
