<?php

namespace AppBundle\Repository;

/**
 * SpaceshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpaceshipRepository extends \Doctrine\ORM\EntityRepository
{
}
